<a href="https://colab.research.google.com/github/Zarak00/Data690_fall2022/blob/main/assignment_05/assignment_05_Missing_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Zarak Mahmood
- 10/1/2022

- Assignment 05

# Missing Data


In [1]:
import numpy as np
import pandas as pd

What does "missing data" mean? What is a missing value? It depends on the origin of the data and the context it was generated. For example, for a survey, a Salary field with an empty value, or a number 0, or an invalid value (a string for example) can be considered "missing data". These concepts are related to the values that Python will consider "Falsy":

In [2]:
falsy_values = (0, False, None, '', [], {})


For Python, all the values above are considered "falsy":



In [3]:
any(falsy_values)


False

Numpy has a special "nullable" value for numbers which is np.nan. It's NaN: "Not a number"



In [4]:
np.nan


nan

The np.nan value is kind of a virus. Everything that it touches becomes np.nan:



In [5]:
3 + np.nan


nan

In [6]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])


In [7]:
a.sum()


nan

In [8]:
a.mean()


nan

For a numeric array, the None value is replaced by np.nan:




In [10]:
a = np.array([1, 2, 3, np.nan, None, 4], dtype='float')


In [11]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

As we said, np.nan is like a virus. If you have any nan value in an array and you try to perform an operation on it, you'll get unexpected results:



In [12]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])


In [13]:
a.mean()


nan

In [14]:
a.sum()

nan

#Numpy also supports an "Infinite" type:



In [15]:
np.inf


inf

Which also behaves as a virus:



In [16]:
3 + np.inf


inf

In [17]:
np.inf / 3


inf

In [18]:
np.inf / np.inf


nan

In [19]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=np.float)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [20]:
b.sum()


nan

#Checking for nan or inf
There are two functions: np.isnan and np.isinf that will perform the desired checks:



In [21]:
np.isnan(np.nan)


True

In [22]:
np.isinf(np.inf)


True

And the joint operation can be performed with np.isfinite.



In [23]:
np.isfinite(np.nan), np.isfinite(np.inf)


(False, False)

#np.isnan and np.isinf also take arrays as inputs, and return boolean arrays as results:



In [24]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))


array([False, False, False,  True, False, False])

In [25]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))


array([False, False, False, False,  True, False])

In [26]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))


array([ True,  True,  True, False, False,  True])